version: 2
updates:
  # Para projetos Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"

  # Para Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
