version: 2
updates:
  # Para projetos Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # Para projetos .NET
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

  # Para Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
